
package webservicegen;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuctionWS", targetNamespace = "http://webserviceserver.auction/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuctionWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns webservicegen.Item
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItem", targetNamespace = "http://webserviceserver.auction/", className = "webservicegen.GetItem")
    @ResponseWrapper(localName = "getItemResponse", targetNamespace = "http://webserviceserver.auction/", className = "webservicegen.GetItemResponse")
    @Action(input = "http://webserviceserver.auction/AuctionWS/getItemRequest", output = "http://webserviceserver.auction/AuctionWS/getItemResponse")
    public Item getItem(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservicegen.Category
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "newCategory", targetNamespace = "http://webserviceserver.auction/", className = "webservicegen.NewCategory")
    @ResponseWrapper(localName = "newCategoryResponse", targetNamespace = "http://webserviceserver.auction/", className = "webservicegen.NewCategoryResponse")
    @Action(input = "http://webserviceserver.auction/AuctionWS/newCategoryRequest", output = "http://webserviceserver.auction/AuctionWS/newCategoryResponse")
    public Category newCategory(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "revokeItem", targetNamespace = "http://webserviceserver.auction/", className = "webservicegen.RevokeItem")
    @ResponseWrapper(localName = "revokeItemResponse", targetNamespace = "http://webserviceserver.auction/", className = "webservicegen.RevokeItemResponse")
    @Action(input = "http://webserviceserver.auction/AuctionWS/revokeItemRequest", output = "http://webserviceserver.auction/AuctionWS/revokeItemResponse")
    public boolean revokeItem(
        @WebParam(name = "arg0", targetNamespace = "")
        Item arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns webservicegen.Money
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "newMoney", targetNamespace = "http://webserviceserver.auction/", className = "webservicegen.NewMoney")
    @ResponseWrapper(localName = "newMoneyResponse", targetNamespace = "http://webserviceserver.auction/", className = "webservicegen.NewMoneyResponse")
    @Action(input = "http://webserviceserver.auction/AuctionWS/newMoneyRequest", output = "http://webserviceserver.auction/AuctionWS/newMoneyResponse")
    public Money newMoney(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns webservicegen.Item
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "offerItem", targetNamespace = "http://webserviceserver.auction/", className = "webservicegen.OfferItem")
    @ResponseWrapper(localName = "offerItemResponse", targetNamespace = "http://webserviceserver.auction/", className = "webservicegen.OfferItemResponse")
    @Action(input = "http://webserviceserver.auction/AuctionWS/offerItemRequest", output = "http://webserviceserver.auction/AuctionWS/offerItemResponse")
    public Item offerItem(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Category arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns webservicegen.Bid
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "newBid", targetNamespace = "http://webserviceserver.auction/", className = "webservicegen.NewBid")
    @ResponseWrapper(localName = "newBidResponse", targetNamespace = "http://webserviceserver.auction/", className = "webservicegen.NewBidResponse")
    @Action(input = "http://webserviceserver.auction/AuctionWS/newBidRequest", output = "http://webserviceserver.auction/AuctionWS/newBidResponse")
    public Bid newBid(
        @WebParam(name = "arg0", targetNamespace = "")
        Item arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        User arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Money arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<webservicegen.Item>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findItemByDescription", targetNamespace = "http://webserviceserver.auction/", className = "webservicegen.FindItemByDescription")
    @ResponseWrapper(localName = "findItemByDescriptionResponse", targetNamespace = "http://webserviceserver.auction/", className = "webservicegen.FindItemByDescriptionResponse")
    @Action(input = "http://webserviceserver.auction/AuctionWS/findItemByDescriptionRequest", output = "http://webserviceserver.auction/AuctionWS/findItemByDescriptionResponse")
    public List<Item> findItemByDescription(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
