
package webservicegen;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RegistrationWS", targetNamespace = "http://webserviceserver.auction/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RegistrationWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns webservicegen.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerUser", targetNamespace = "http://webserviceserver.auction/", className = "webservicegen.RegisterUser")
    @ResponseWrapper(localName = "registerUserResponse", targetNamespace = "http://webserviceserver.auction/", className = "webservicegen.RegisterUserResponse")
    @Action(input = "http://webserviceserver.auction/RegistrationWS/registerUserRequest", output = "http://webserviceserver.auction/RegistrationWS/registerUserResponse")
    public User registerUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns webservicegen.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://webserviceserver.auction/", className = "webservicegen.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://webserviceserver.auction/", className = "webservicegen.GetUserResponse")
    @Action(input = "http://webserviceserver.auction/RegistrationWS/getUserRequest", output = "http://webserviceserver.auction/RegistrationWS/getUserResponse")
    public User getUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<webservicegen.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://webserviceserver.auction/", className = "webservicegen.GetUsers")
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://webserviceserver.auction/", className = "webservicegen.GetUsersResponse")
    @Action(input = "http://webserviceserver.auction/RegistrationWS/getUsersRequest", output = "http://webserviceserver.auction/RegistrationWS/getUsersResponse")
    public List<User> getUsers();

}
